---
title: "KDX"
author: "Deukjung"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

#준비하기
```{r}
library(tidyverse) # 데이터 가공 및 시각화
library(readxl) # 엑셀파일 불러오기 패키지
library(ggplot2)
library(lubridate)
library(dplyr)
library(zoo)
library(modelr)
options(na.action = na.warn)
library(pastecs)
library(WRS)
library(utils)
```

# 데이터 불러오기 및 통합
```{r}
files <- list.files(path = "data/Mcorporation/상품 카테고리 데이터_KDX 시각화 경진대회 Only", pattern = "*.xlsx", full.names = T)

products <- sapply(files, read_excel, simplify=FALSE) %>% 
  bind_rows(.id = "id") %>% 
  select(-id)

glimpse(products)
```


#기술적 통계량
```{r}
#고객성별 요약
products %>%
  filter(고객성별 != "없음") %>%
  select(고객성별, 구매금액, 구매수) %>%
  group_by(고객성별) %>%
  summarize(구매금액평균 = mean(구매금액), 구매수평균 = mean(구매수)) %>%
  mutate(금액비율 = 구매금액평균 * 100 / sum(구매금액평균), 수량비율 = 구매수평균 * 100 / sum(구매수평균))

#OS유형별 요약
products %>%
  filter(OS유형 != "없음") %>%
  select(OS유형, 구매금액, 구매수) %>%
  group_by(OS유형) %>%
  summarize(구매금액평균 = mean(구매금액), 구매수평균 = mean(구매수)) %>%
  mutate(금액비율 = 구매금액평균 * 100 / sum(구매금액평균), 수량비율 = 구매수평균 * 100 / sum(구매수평균))

#고객나이별 요약
products %>%
  filter(고객나이 > 0 & 고객나이 < 80) %>%
  select(고객나이, 구매금액, 구매수) %>%
  mutate(금액비율 = 구매금액 * 100 / sum(구매금액), 수량비율 = 구매수 * 100 / sum(구매수)) %>%
  group_by(고객나이) %>%
  summarize(구매금액평균 = mean(구매금액), 구매수평균 = mean(구매수), 금액비 = sum(금액비율), 수량비 = sum(수량비율))

#카테고리별 요약
products %>%
  select(카테고리명, 구매금액, 구매수) %>%
  group_by(카테고리명) %>%
  summarize(구매금액평균 = mean(구매금액)) %>%
  mutate(금액비율 = 구매금액평균 * 100 / sum(구매금액평균)) %>%
  arrange(desc(구매금액평균)) %>%
  head(10)

products %>%  #구매금액 총합
  select(카테고리명, 구매금액, 구매수) %>%
  group_by(카테고리명) %>%
  summarize(구매금액평균 = mean(구매금액)) %>%
  summarize(평균합 = sum(구매금액평균))


products %>%
  select(카테고리명, 구매금액, 구매수) %>%
  group_by(카테고리명) %>%
  summarize(구매수평균 = mean(구매수)) %>%
  mutate(금매수비율 = 구매수평균 * 100 / sum(구매수평균)) %>%
  arrange(desc(구매수평균)) %>%
  head(10)

products %>%  #구매수 평균 총합
  select(카테고리명, 구매금액, 구매수) %>%
  group_by(카테고리명) %>%
  summarize(구매수평균 = mean(구매수)) %>%
  summarize(평균합 = sum(구매수평균))
```


#OS별 매달 구매금액 변화 그래프
```{r}
products2 <- products %>% 
  mutate(년월 = as.yearmon(as.character(구매날짜), "%Y%m")) %>%
  rename(date = "년월") %>%
  filter(OS유형 != "없음") %>%
  group_by(date, OS유형) %>%
  summarise(mean = mean(구매금액))

products_line <- products2 %>% 
  data_grid(date, OS유형) %>%
  gather_predictions(lm(mean ~ date * OS유형, data = products2))

products2 %>%
  ggplot(aes(date, mean, colour = OS유형)) +
  geom_line(lwd = 2) +
  geom_line(data = products_line, aes(y = pred),lwd = 1) +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold")) +
  labs(title="OS 유형별 월별 소비패턴 동향", 
       y="Avg. Sales (1000)") +
  theme(legend.title = element_text(size = 15, face = "bold")) +
  theme(legend.text = element_text(size = 12))
```

#안드로이드의 카테고리별 구매금액
```{r}
products %>%
  filter(OS유형 == "안드로이드") %>%
  group_by(카테고리명, OS유형) %>%
  summarise(mean = mean(구매금액)) %>%
  arrange(desc(mean)) %>%
  head(10) %>%
  ggplot(aes(x = 카테고리명, y = mean)) +
  geom_bar(stat="identity", position = "dodge", width=.5, fill = "steelblue") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6,)) + 
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold")) +
  labs(title="안드로이드", 
       subtitle="카테고리명 Vs Avg. 구매금액 by OS유형", 
       caption="source: products")
```

#IOS의 카테고리별 구매금액
```{r}
products %>%
  filter(OS유형 == "IOS") %>%
  group_by(카테고리명, OS유형) %>%
  summarise(mean = mean(구매금액)) %>%
  arrange(desc(mean)) %>%
  head(10) %>%
  ggplot(aes(x = 카테고리명, y = mean)) +
  geom_bar(stat="identity", position = "dodge", width=.5, fill = "#fc9272") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6,)) + 
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold")) +
  labs(title="IOS", 
       subtitle="카테고리명 Vs Avg. 구매금액 by OS유형", 
       caption="source: products")
```

#안드로이드와 IOS 나이대별 구매금액
```{r}
products %>%
  filter(OS유형 == "안드로이드" | OS유형 == "IOS") %>%
  filter(고객나이 > 0 & 고객나이 < 80) %>%
  group_by(고객나이, OS유형) %>%
  summarise(mean = mean(구매금액)) %>%
  ggplot(aes(x = 고객나이, y = mean, fill = OS유형)) +
  geom_bar(stat="identity", position = "dodge", width=5) + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold")) +
  labs(title="Android", 
       subtitle="카테고리명 Vs Avg. 구매금액 by OS유형", 
       caption="source: products")
```

#독립 t검정
```{r}
#데이터 필터링
products1 <- products %>%
  mutate(년월 = as.yearmon(as.character(구매날짜), "%Y%m")) %>%
  rename(date = "년월") %>%
  filter(OS유형 == "IOS" | OS유형 == "안드로이드") %>%
  group_by(date, OS유형) %>%
  summarise(mean = mean(구매금액))

glimpse(products1)

#평균과 표준오차
by(products1$mean, products1$OS유형, stat.desc, basic = FALSE, norm = TRUE)

#t.test()
ind.t.test<-t.test(mean ~ OS유형, data = products1)

ind.t.test
```


